load(
    "@rules_rust//rust:defs.bzl",
    "rust_doc",
    "rust_doc_test",
    "rust_library",
    "rust_test",
)

rust_library(
    name = "nativelink-nix",
    srcs = [
        "src/lib.rs",
        "src/narinfo.rs",
        "src/nixbase32.rs",
        "src/signing.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nativelink-error",
        "@crates//:base64",
        "@crates//:ed25519-dalek",
        "@crates//:hex",
    ],
)

rust_test(
    name = "unit_test",
    timeout = "short",
    crate = ":nativelink-nix",
    deps = [
        "//nativelink-error",
        "@crates//:base64",
        "@crates//:ed25519-dalek",
        "@crates//:hex",
    ],
)

rust_doc(
    name = "docs",
    crate = ":nativelink-nix",
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    timeout = "short",
    crate = ":nativelink-nix",
)
