#:schema ../tools/cargo-with-detailed-deps.json
lints.workspace = true

[package]
edition = "2024"
name = "nativelink-service"
version = "1.7.3"

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-error = { path = "../nativelink-error" }
nativelink-metric = { path = "../nativelink-metric" }
nativelink-nix = { path = "../nativelink-nix" }
nativelink-oci = { path = "../nativelink-oci" }
nativelink-oci-registry = { path = "../nativelink-oci-registry" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-scheduler = { path = "../nativelink-scheduler" }
nativelink-store = { path = "../nativelink-store" }
nativelink-util = { path = "../nativelink-util" }

async-compression = { version = "0.4.25", default-features = false, features = [
  "bzip2",
  "gzip",
  "tokio",
  "xz",
  "zstd",
] }
axum = { version = "0.8.3", default-features = false }
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
blake3 = { version = "1.8.0", default-features = false }
bytes = { version = "1.10.1", default-features = false }
ed25519-dalek = { version = "2.2.0", default-features = false, features = [
  "std",
] }
fastcdc = { version = "3.2.1", default-features = false, features = ["tokio"] }
futures = { version = "0.3.31", default-features = false }
hex = { version = "0.4.3", default-features = false }
http-body-util = { version = "0.1.3", default-features = false }
hyper = { version = "1.6.0", default-features = false, features = [
  "http1",
  "server",
] }
hyper-util = { version = "0.1.11", default-features = false, features = [
  "tokio",
] }
opentelemetry = { version = "0.32.0", default-features = false }
opentelemetry-semantic-conventions = { version = "0.32.0", default-features = false, features = [
  "default",
  "semconv_experimental",
] }
parking_lot = { version = "0.12.3", default-features = false }
prost = { version = "0.14.4", default-features = false }
prost-types = { version = "0.14.4", default-features = false, features = [
  "std",
] }
rand = { version = "0.9.0", default-features = false, features = [
  "thread_rng",
] }
rcgen = { version = "0.14.2", default-features = false, features = [
  "pem",
  "ring",
] }
reqwest = { version = "0.13", default-features = false, features = [
  "rustls",
  "stream",
] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.140", default-features = false, features = [
  "std",
] }
serde_json5 = { version = "0.2.1", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
tokio = { version = "1.52.2", features = [
  "fs",
  "io-util",
  "net",
  "rt-multi-thread",
  "signal",
], default-features = false }
tokio-rustls = { version = "0.26.2", default-features = false, features = [
  "ring",
] }
tokio-stream = { version = "0.1.17", features = [
  "fs",
], default-features = false }
tokio-util = { version = "0.7.14", features = ["io"], default-features = false }
tonic = { version = "0.14.0", features = [
  "gzip",
  "router",
  "tls-ring",
  "transport",
], default-features = false }
tower = { version = "0.5.2", default-features = false }
tracing = { version = "0.1.41", default-features = false }
uuid = { version = "1.16.0", default-features = false, features = [
  "serde",
  "v4",
] }
zstd = { version = "0.13.3", default-features = false }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

async-lock = { version = "3.4.0", features = ["std"], default-features = false }
async-trait = { version = "0.1.88", default-features = false }
axum = { version = "0.8.3", default-features = false, features = [
  "http1",
  "tokio",
] }
hex = { version = "0.4.3", default-features = false }
hyper = { version = "1.6.0", default-features = false }
hyper-util = { version = "0.1.11", default-features = false }
pretty_assertions = { version = "1.4.1", features = [
  "std",
], default-features = false }
proptest = { version = "1", default-features = false, features = [
  "bit-set",
  "std",
] }
serde_json = { version = "1.0.140", default-features = false, features = [
  "std",
] }
sha2 = { version = "0.10.8", default-features = false }
tokio = { version = "1.52.2", features = [
  "net",
  "test-util",
], default-features = false }
tonic-prost = { version = "0.14.6", default-features = false }
tracing-test = { version = "0.2.5", default-features = false, features = [
  "no-env-filter",
] }

[package.metadata.cargo-machete]
# Used by nativelink_test macro
ignored = ["tracing-test"]
