module(
    name = "nativelink-bazel-template",
    version = "0",
    compatibility_level = 0,
)

# Keep the commit in sync with the NativeLink input from `flake.nix`.
bazel_dep(name = "local-remote-execution", version = "0")
git_override(
    module_name = "local-remote-execution",
    commit = "a8822ee3083d59d54f9f0f091ee8c3df5e44d324",
    remote = "ssh://git@git.s4.gl/straylight/straylight-nativelink.git",
    strip_prefix = "local-remote-execution",
)

bazel_dep(name = "rules_cc", version = "0.2.8")
